-- Sonokai (sainnhe/sonokai "default" style, transparent background) as a lush spec.
-- Generated once from sonokai b023c52; from now on this file is the source of the colorscheme.
-- Edit it (:Lushify in this buffer previews changes live), then run :Shipwright from
-- ~/.config/nvim to rebuild the static colors/sonokai.lua.
--
-- Covers the editor UI, treesitter, LSP, the plugins in this config and regex syntax for
-- filetypes without a treesitter parser here; sonokai's groups for other plugins are left out.

local lush = require("lush")
local hsl = lush.hsl

-- Plain hex strings: lush.hsl() keeps integer H/S/L and would shift these by a unit or two.
-- For derived colors wrap one in hsl(), e.g. fg = hsl(p.red).darken(10).
local p = {
  fg = "#e2e2e3",
  red = "#fc5d7c",
  orange = "#f39660",
  yellow = "#e7c664",
  green = "#9ed072",
  blue = "#76cce0",
  purple = "#b39df3",
  grey = "#7f8490",
  grey_dim = "#595f6f",
  black = "#181819",
  bg0 = "#2c2e34",
  bg1 = "#33353f",
  bg2 = "#363944",
  bg3 = "#3b3e48",
  bg4 = "#414550",
  bg_red = "#55393d",
  bg_green = "#394634",
  bg_blue = "#354157",
  filled_red = "#ff6077",
  filled_green = "#a7df78",
  filled_blue = "#85d3f2",
}

---@diagnostic disable: undefined-global
return lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    -- Sonokai's helper groups: most groups below link to these
    Blue { fg = p.blue },
    BlueItalic { fg = p.blue },
    BlueSign { fg = p.blue },
    CurrentWord { bold = true },
    ErrorFloat { fg = p.red },
    Fg { fg = p.fg },
    Green { fg = p.green },
    GreenSign { fg = p.green },
    Grey { fg = p.grey },
    HintFloat { fg = p.purple },
    htmlTSText { Fg },
    InfoFloat { fg = p.blue },
    LineNr { fg = p.grey_dim },
    InlayHints { LineNr },
    luaBraces { Fg },
    luaTSConstructor { luaBraces },
    markdownH1 { fg = p.red, bold = true },
    markdownH2 { fg = p.orange, bold = true },
    markdownH3 { fg = p.yellow, bold = true },
    markdownH4 { fg = p.green, bold = true },
    markdownH5 { fg = p.blue, bold = true },
    markdownH6 { fg = p.purple, bold = true },
    OkFloat { fg = p.green },
    Orange { fg = p.orange },
    OrangeItalic { fg = p.orange },
    Purple { fg = p.purple },
    PurpleItalic { fg = p.purple },
    PurpleSign { fg = p.purple },
    Red { fg = p.red },
    RedItalic { fg = p.red },
    RedSign { fg = p.red },
    TSDanger { fg = p.bg0, bg = p.red, bold = true },
    TSEmphasis { italic = true },
    TSNote { fg = p.bg0, bg = p.green, bold = true },
    TSStrong { bold = true },
    TSUnderline { underline = true },
    TSURI { fg = p.blue, underline = true },
    TSWarning { fg = p.bg0, bg = p.yellow, bold = true },
    tsxTSConstructor { BlueItalic },
    tsxTSTag { OrangeItalic },
    VirtualTextError { Grey },
    VirtualTextHint { Grey },
    VirtualTextInfo { Grey },
    VirtualTextOk { Grey },
    VirtualTextWarning { Grey },
    WarningFloat { fg = p.yellow },
    Yellow { fg = p.yellow },
    YellowSign { fg = p.yellow },

    -- Editor UI and legacy syntax groups
    Added { Green },
    Boolean { fg = p.purple },
    Changed { Blue },
    Character { fg = p.yellow },
    ColorColumn { bg = p.bg1 },
    Comment { fg = p.grey, italic = true },
    Conceal { fg = p.grey_dim },
    Conditional { fg = p.red },
    Constant { fg = p.orange },
    IncSearch { fg = p.bg0, bg = p.filled_red },
    CurSearch { IncSearch },
    Cursor { bg = p.fg },
    CursorColumn { bg = p.bg1 },
    CursorLine { bg = p.bg1 },
    CursorLineNr { fg = p.fg },
    Debug { fg = p.yellow },
    Define { fg = p.red },
    Delimiter { fg = p.fg },
    DiagnosticDeprecated { sp = p.fg, strikethrough = true },
    DiagnosticError { fg = p.red },
    DiagnosticFloatingError { ErrorFloat },
    DiagnosticFloatingHint { HintFloat },
    DiagnosticFloatingInfo { InfoFloat },
    DiagnosticFloatingOk { OkFloat },
    DiagnosticFloatingWarn { WarningFloat },
    DiagnosticHint { fg = p.purple },
    DiagnosticInfo { fg = p.blue },
    DiagnosticOk { fg = p.green },
    DiagnosticSignError { RedSign },
    DiagnosticSignHint { PurpleSign },
    DiagnosticSignInfo { BlueSign },
    DiagnosticSignOk { GreenSign },
    DiagnosticSignWarn { YellowSign },
    DiagnosticUnderlineError { sp = p.red, undercurl = true },
    DiagnosticUnderlineHint { sp = p.purple, undercurl = true },
    DiagnosticUnderlineInfo { sp = p.blue, undercurl = true },
    DiagnosticUnderlineOk { sp = p.green, undercurl = true },
    DiagnosticUnderlineWarn { sp = p.yellow, undercurl = true },
    DiagnosticUnnecessary { fg = p.grey },
    DiagnosticVirtualTextError { VirtualTextError },
    DiagnosticVirtualTextHint { VirtualTextHint },
    DiagnosticVirtualTextInfo { VirtualTextInfo },
    DiagnosticVirtualTextOk { VirtualTextOk },
    DiagnosticVirtualTextWarn { VirtualTextWarning },
    DiagnosticWarn { fg = p.yellow },
    DiffAdd { bg = p.bg_green },
    DiffChange { bg = p.bg_blue },
    DiffDelete { bg = p.bg_red },
    DiffText { fg = p.bg0, bg = p.blue },
    Directory { fg = p.green },
    EndOfBuffer { fg = p.bg4 },
    Error { fg = p.red },
    ErrorMsg { fg = p.red, bold = true, underline = true },
    Exception { fg = p.red },
    Float { fg = p.purple },
    FloatBorder { fg = p.grey, bg = p.bg2 },
    FloatTitle { fg = p.red, bg = p.bg4, bold = true },
    FoldColumn { fg = p.grey_dim },
    Folded { fg = p.grey },
    Function { fg = p.green },
    Identifier { fg = p.orange },
    Ignore { fg = p.grey },
    Include { fg = p.red },
    Keyword { fg = p.red },
    Label { fg = p.purple },
    lCursor { Cursor },
    LspCodeLens { VirtualTextInfo },
    LspCodeLensSeparator { VirtualTextHint },
    LspInlayHint { InlayHints },
    LspReferenceRead { CurrentWord },
    LspReferenceText { CurrentWord },
    LspReferenceWrite { CurrentWord },
    Search { fg = p.bg0, bg = p.filled_green },
    LspSignatureActiveParameter { Search },
    Macro { fg = p.purple },
    MatchParen { bg = p.bg4 },
    ModeMsg { fg = p.fg, bold = true },
    MoreMsg { fg = p.blue, bold = true },
    NonText { fg = p.bg4 },
    Normal { fg = p.fg },
    NormalFloat { fg = p.fg, bg = p.bg2 },
    NormalNC { fg = p.fg },
    Number { fg = p.purple },
    Operator { fg = p.red },
    Pmenu { fg = p.fg, bg = p.bg2 },
    PmenuExtra { fg = p.grey, bg = p.bg2 },
    PmenuKind { fg = p.green, bg = p.bg2 },
    PmenuSbar { bg = p.bg2 },
    PmenuSel { fg = p.bg0, bg = p.filled_blue, blend = 0 },
    PmenuThumb { bg = p.grey },
    PreCondit { fg = p.red },
    PreProc { fg = p.red },
    Question { fg = p.yellow },
    QuickFixLine { fg = p.blue, bold = true },
    Removed { Red },
    Repeat { fg = p.red },
    SignColumn { fg = p.fg },
    Special { fg = p.purple },
    SpecialChar { fg = p.purple },
    SpecialComment { fg = p.grey, italic = true },
    SpecialKey { fg = p.purple },
    SpellBad { sp = p.red, undercurl = true },
    SpellCap { sp = p.yellow, undercurl = true },
    SpellLocal { sp = p.blue, undercurl = true },
    SpellRare { sp = p.purple, undercurl = true },
    Statement { fg = p.red },
    StatusLine { fg = p.fg, bg = p.bg3 },
    StatusLineNC { fg = p.grey, bg = p.bg1 },
    StatusLineTerm { fg = p.fg, bg = p.bg3 },
    StatusLineTermNC { fg = p.grey, bg = p.bg1 },
    StorageClass { fg = p.blue },
    String { fg = p.yellow },
    Structure { fg = p.blue },
    Substitute { fg = p.bg0, bg = p.yellow },
    TabLine { fg = p.fg, bg = p.bg4 },
    TabLineFill { fg = p.grey, bg = p.bg1 },
    TabLineSel { fg = p.bg0, bg = p.filled_red },
    Tag { fg = p.orange },
    TermCursor { Cursor },
    Title { fg = p.red, bold = true },
    Todo { fg = p.bg0, bg = p.blue, bold = true },
    Type { fg = p.blue },
    Typedef { fg = p.red },
    Underlined { underline = true },
    VertSplit { fg = p.black },
    Visual { bg = p.bg4 },
    VisualNOS { bg = p.bg4, underline = true },
    WarningMsg { fg = p.yellow, bold = true },
    Whitespace { fg = p.bg4 },
    WinBar { fg = p.fg, bg = p.bg3, bold = true },
    WinBarNC { fg = p.grey, bg = p.bg1 },
    WinSeparator { VertSplit },

    -- Treesitter captures
    sym"@annotation" { BlueItalic },
    sym"@attribute" { BlueItalic },
    sym"@attribute.builtin" { Special },
    sym"@boolean" { Purple },
    sym"@character" { Yellow },
    sym"@character.printf" { SpecialChar },
    sym"@character.special" { SpecialChar },
    sym"@comment" { Comment },
    sym"@comment.error" { TSDanger },
    sym"@comment.note" { TSNote },
    sym"@comment.todo" { Todo },
    sym"@comment.warning" { TSWarning },
    sym"@conceal" { Grey },
    sym"@conditional" { Red },
    sym"@constant" { Fg },
    sym"@constant.builtin" { PurpleItalic },
    sym"@constant.macro" { PurpleItalic },
    sym"@constructor" { Green },
    sym"@constructor.lua" { luaTSConstructor },
    sym"@constructor.tsx" { tsxTSConstructor },
    sym"@debug" { Debug },
    sym"@define" { Define },
    diffChanged { Changed },
    sym"@diff.delta" { diffChanged },
    diffRemoved { Removed },
    sym"@diff.minus" { diffRemoved },
    diffAdded { Added },
    sym"@diff.plus" { diffAdded },
    sym"@error" { Error },
    sym"@exception" { Red },
    sym"@field" { Orange },
    sym"@float" { Purple },
    sym"@function" { Green },
    sym"@function.builtin" { Green },
    sym"@function.call" { Green },
    sym"@function.macro" { Green },
    sym"@function.method" { Green },
    sym"@function.method.call" { Green },
    sym"@include" { Red },
    sym"@keyword" { Red },
    sym"@keyword.conditional" { Red },
    sym"@keyword.debug" { Debug },
    sym"@keyword.directive" { PreProc },
    sym"@keyword.directive.define" { Define },
    sym"@keyword.exception" { Red },
    sym"@keyword.function" { Red },
    sym"@keyword.import" { Red },
    sym"@keyword.operator" { Red },
    sym"@keyword.repeat" { Red },
    sym"@keyword.return" { Red },
    sym"@keyword.storage" { Red },
    sym"@label" { Red },
    sym"@markup" { Special },
    sym"@markup.emphasis" { TSEmphasis },
    sym"@markup.environment" { Macro },
    sym"@markup.environment.name" { Type },
    sym"@markup.heading" { Title },
    sym"@markup.heading.1.delimiter.vimdoc" { sp = p.fg, underdouble = true, nocombine = true },
    sym"@markup.heading.1.markdown" { markdownH1 },
    sym"@markup.heading.1.marker.markdown" { sym"@conceal" },
    sym"@markup.heading.2.delimiter.vimdoc" { sp = p.fg, underline = true, nocombine = true },
    sym"@markup.heading.2.markdown" { markdownH2 },
    sym"@markup.heading.2.marker.markdown" { sym"@conceal" },
    sym"@markup.heading.3.markdown" { markdownH3 },
    sym"@markup.heading.3.marker.markdown" { sym"@conceal" },
    sym"@markup.heading.4.markdown" { markdownH4 },
    sym"@markup.heading.4.marker.markdown" { sym"@conceal" },
    sym"@markup.heading.5.markdown" { markdownH5 },
    sym"@markup.heading.5.marker.markdown" { sym"@conceal" },
    sym"@markup.heading.6.markdown" { markdownH6 },
    sym"@markup.heading.6.marker.markdown" { sym"@conceal" },
    sym"@markup.italic" { italic = true },
    sym"@markup.link" { Constant },
    sym"@markup.link.label" { SpecialChar },
    sym"@markup.link.url" { TSURI },
    sym"@markup.list" { Yellow },
    sym"@markup.list.checked" { Green },
    sym"@markup.list.unchecked" { Ignore },
    sym"@markup.math" { Yellow },
    sym"@markup.note" { TSNote },
    sym"@markup.quote" { Grey },
    sym"@markup.raw" { String },
    sym"@markup.strike" { Grey },
    sym"@markup.strikethrough" { strikethrough = true },
    sym"@markup.strong" { TSStrong },
    sym"@markup.underline" { TSUnderline },
    sym"@math" { Yellow },
    sym"@method" { Green },
    sym"@method.call" { Green },
    sym"@module" { BlueItalic },
    sym"@module.builtin" { Special },
    sym"@namespace" { BlueItalic },
    sym"@none" { Fg },
    sym"@number" { Purple },
    sym"@number.float" { Purple },
    sym"@operator" { Red },
    sym"@parameter" { Fg },
    sym"@parameter.reference" { Fg },
    sym"@preproc" { PreProc },
    sym"@property" { Orange },
    sym"@punctuation" { Delimiter },
    sym"@punctuation.bracket" { Grey },
    sym"@punctuation.delimiter" { Grey },
    sym"@punctuation.special" { Yellow },
    sym"@repeat" { Red },
    sym"@storageclass" { Red },
    sym"@storageclass.lifetime" { Red },
    sym"@strike" { Grey },
    sym"@string" { Yellow },
    sym"@string.escape" { Green },
    sym"@string.regex" { Green },
    sym"@string.regexp" { Green },
    sym"@string.special" { SpecialChar },
    sym"@string.special.symbol" { Fg },
    sym"@string.special.symbol.elixir" { Orange },
    sym"@string.special.symbol.ruby" { Orange },
    sym"@string.special.uri" { TSURI },
    sym"@string.special.url" { Underlined },
    sym"@symbol" { Fg },
    sym"@tag" { BlueItalic },
    sym"@tag.attribute" { Green },
    sym"@tag.builtin" { Special },
    sym"@tag.delimiter" { Red },
    sym"@tag.tsx" { tsxTSTag },
    sym"@text" { Green },
    sym"@text.danger" { TSDanger },
    sym"@text.diff.add" { diffAdded },
    sym"@text.diff.delete" { diffRemoved },
    sym"@text.emphasis" { TSEmphasis },
    sym"@text.environment" { Macro },
    sym"@text.environment.name" { Type },
    sym"@text.gitcommit" { Fg },
    sym"@text.html" { htmlTSText },
    sym"@text.literal" { String },
    sym"@text.math" { Yellow },
    sym"@text.note" { TSNote },
    sym"@text.reference" { Constant },
    sym"@text.strike" { Grey },
    sym"@text.strong" { TSStrong },
    sym"@text.title" { Title },
    sym"@text.todo" { Todo },
    sym"@text.todo.checked" { Green },
    sym"@text.todo.unchecked" { Ignore },
    sym"@text.underline" { TSUnderline },
    sym"@text.uri" { TSURI },
    sym"@text.warning" { TSWarning },
    sym"@todo" { Todo },
    sym"@type" { BlueItalic },
    sym"@type.builtin" { BlueItalic },
    sym"@type.definition" { BlueItalic },
    sym"@type.qualifier" { Red },
    sym"@uri" { TSURI },
    sym"@variable" { Fg },
    sym"@variable.builtin" { PurpleItalic },
    sym"@variable.member" { Orange },
    sym"@variable.parameter" { Fg },
    sym"@variable.parameter.builtin" { Special },

    -- LSP semantic tokens
    sym"@lsp.mod.deprecated" { DiagnosticDeprecated },
    sym"@lsp.type.class" { BlueItalic },
    sym"@lsp.type.comment" { Comment },
    sym"@lsp.type.decorator" { Green },
    sym"@lsp.type.enum" { BlueItalic },
    sym"@lsp.type.enumMember" { Orange },
    sym"@lsp.type.event" { sym"@type" },
    sym"@lsp.type.events" { Red },
    sym"@lsp.type.function" { Green },
    sym"@lsp.type.interface" { BlueItalic },
    sym"@lsp.type.keyword" { Red },
    sym"@lsp.type.macro" { PurpleItalic },
    sym"@lsp.type.method" { Green },
    sym"@lsp.type.modifier" { Red },
    sym"@lsp.type.namespace" { BlueItalic },
    sym"@lsp.type.number" { Purple },
    sym"@lsp.type.operator" { Red },
    sym"@lsp.type.parameter" { Fg },
    sym"@lsp.type.property" { Orange },
    sym"@lsp.type.regexp" { Green },
    sym"@lsp.type.string" { Yellow },
    sym"@lsp.type.struct" { BlueItalic },
    sym"@lsp.type.type" { BlueItalic },
    sym"@lsp.type.typeParameter" { BlueItalic },
    sym"@lsp.type.variable" { Fg },
    sym"@lsp.typemod.variable.defaultLibrary.javascript" { PurpleItalic },
    sym"@lsp.typemod.variable.defaultLibrary.javascriptreact" { PurpleItalic },
    sym"@lsp.typemod.variable.defaultLibrary.typescript" { PurpleItalic },
    sym"@lsp.typemod.variable.defaultLibrary.typescriptreact" { PurpleItalic },

    -- Plugins: snacks, blink.cmp, neo-tree, trouble
    BlinkCmpGhostText { Conceal },
    BlinkCmpKindArray { Yellow },
    BlinkCmpKindBoolean { Yellow },
    BlinkCmpKindClass { Blue },
    BlinkCmpKindColor { Yellow },
    BlinkCmpKindConstant { Orange },
    BlinkCmpKindConstructor { Green },
    BlinkCmpKindDefault { Yellow },
    BlinkCmpKindEnum { Blue },
    BlinkCmpKindEnumMember { Purple },
    BlinkCmpKindEvent { Yellow },
    BlinkCmpKindField { Green },
    BlinkCmpKindFile { Green },
    BlinkCmpKindFolder { Yellow },
    BlinkCmpKindFunction { Green },
    BlinkCmpKindInterface { Blue },
    BlinkCmpKindKey { Red },
    BlinkCmpKindKeyword { Red },
    BlinkCmpKindMethod { Green },
    BlinkCmpKindModule { Blue },
    BlinkCmpKindNamespace { Red },
    BlinkCmpKindNull { Yellow },
    BlinkCmpKindNumber { Yellow },
    BlinkCmpKindObject { Yellow },
    BlinkCmpKindOperator { Red },
    BlinkCmpKindPackage { Red },
    BlinkCmpKindProperty { Orange },
    BlinkCmpKindReference { Yellow },
    BlinkCmpKindSnippet { Yellow },
    BlinkCmpKindString { Yellow },
    BlinkCmpKindStruct { Blue },
    BlinkCmpKindText { Fg },
    BlinkCmpKindTypeParameter { Blue },
    BlinkCmpKindUnit { Purple },
    BlinkCmpKindValue { Purple },
    BlinkCmpKindVariable { Orange },
    BlinkCmpLabelMatch { fg = p.green, bold = true },
    NeoTreeDimText { Grey },
    NeoTreeDirectoryIcon { Blue },
    NeoTreeGitAdded { Green },
    NeoTreeGitConflict { Yellow },
    NeoTreeGitDeleted { Red },
    NeoTreeGitIgnored { Grey },
    NeoTreeGitModified { Blue },
    NeoTreeGitStaged { Purple },
    NeoTreeGitUnstaged { Purple },
    NeoTreeGitUntracked { Fg },
    NeoTreeIndentMarker { NonText },
    NeoTreeRootName { Title },
    SnacksDashboardDesc { Yellow },
    SnacksDashboardDir { Grey },
    SnacksDashboardFile { Blue },
    SnacksDashboardHeader { Blue },
    SnacksDashboardIcon { Blue },
    SnacksDashboardKey { Green },
    SnacksDashboardTitle { RedItalic },
    SnacksPicker { Normal },
    SnacksPickerBorder { Grey },
    SnacksPickerBufFlags { Blue },
    SnacksPickerDir { Comment },
    SnacksPickerTitle { Title },
    SnacksPickerFooter { SnacksPickerTitle },
    SnacksPickerGitStatus { Special },
    SnacksPickerInputCursorLine { Normal },
    SnacksPickerKeymapRhs { Normal },
    SnacksPickerListCursorLine { CursorLine },
    SnacksPickerMatch { fg = p.green, bold = true },
    SnacksPickerSelected { Blue },
    SnacksPickerToggle { Yellow },
    SnacksPickerTotals { Grey },
    TroubleCode { Grey },
    TroubleSource { Grey },
    TroubleText { Fg },

    -- Regex syntax for filetypes without a treesitter parser here
    diffFile { Purple },
    diffIndexLine { Purple },
    diffLine { Grey },
    diffNewFile { Orange },
    diffOldFile { Yellow },
    gitcommitArrow { Grey },
    gitcommitDiscarded { Grey },
    gitcommitFile { Green },
    gitcommitOnBranch { Grey },
    gitcommitSelected { Grey },
    gitcommitSummary { Red },
    gitcommitUnmerged { Grey },
    gitcommitUntracked { Grey },
    phpClass { BlueItalic },
    phpComparison { Red },
    phpDefine { Green },
    phpFunction { Green },
    phpIdentifier { Fg },
    phpInterpSimpleCurly { Purple },
    phpInterpVarname { Fg },
    phpLabel { Red },
    phpMemberSelector { Red },
    phpMethod { Green },
    phpMethodsVar { Fg },
    phpNowDoc { Yellow },
    phpNullValue { OrangeItalic },
    phpParent { Fg },
    phpSpecialFunction { Green },
    phpStructure { Red },
    phpSuperglobals { BlueItalic },
    phpVarSelector { Fg },
    pythonBuiltin { BlueItalic },
    pythonBuiltinFunc { Green },
    pythonBuiltinObj { OrangeItalic },
    pythonBuiltinType { BlueItalic },
    pythonCoding { Grey },
    pythonConditional { Red },
    pythonDecorator { OrangeItalic },
    pythonDecoratorName { OrangeItalic },
    pythonDot { Grey },
    pythonDottedName { OrangeItalic },
    pythonException { Red },
    pythonExceptions { Red },
    pythonExClass { BlueItalic },
    pythonFunction { Green },
    pythonImport { PreProc },
    pythonInclude { Include },
    pythonNone { OrangeItalic },
    pythonOperator { Red },
    pythonRepeat { Red },
    shDerefOff { BlueItalic },
    shDerefSimple { BlueItalic },
    shDerefSpecial { BlueItalic },
    shDerefVar { BlueItalic },
    shFunction { Green },
    shFunctionKey { Red },
    shOption { Purple },
    shQuote { Yellow },
    shRange { Fg },
    shVarAssign { Red },
    shVariable { BlueItalic },
  }
end)
