-- Sonokai, compiled by shipwright (shipwright_build.lua) from the lush spec in
-- lua/lush_theme/sonokai.lua. Change colors there and run :Shipwright; the group table below is
-- overwritten on every build. Loading needs no plugin, only nvim_set_hl calls.

vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "sonokai"

local groups = {
-- PATCH_OPEN
Normal = {fg = "#e2e2e3"},
SnacksPicker = {link = "Normal"},
SnacksPickerInputCursorLine = {link = "Normal"},
SnacksPickerKeymapRhs = {link = "Normal"},
diffAdded = {link = "Added"},
BlinkCmpLabelMatch = {fg = "#9ed072", bold = true},
Blue = {fg = "#76cce0"},
BlinkCmpKindClass = {link = "Blue"},
BlinkCmpKindEnum = {link = "Blue"},
BlinkCmpKindInterface = {link = "Blue"},
BlinkCmpKindModule = {link = "Blue"},
BlinkCmpKindStruct = {link = "Blue"},
BlinkCmpKindTypeParameter = {link = "Blue"},
Changed = {link = "Blue"},
NeoTreeDirectoryIcon = {link = "Blue"},
NeoTreeGitModified = {link = "Blue"},
SnacksDashboardFile = {link = "Blue"},
SnacksDashboardHeader = {link = "Blue"},
SnacksDashboardIcon = {link = "Blue"},
SnacksPickerBufFlags = {link = "Blue"},
SnacksPickerSelected = {link = "Blue"},
BlueItalic = {fg = "#76cce0"},
phpClass = {link = "BlueItalic"},
phpSuperglobals = {link = "BlueItalic"},
pythonBuiltin = {link = "BlueItalic"},
pythonBuiltinType = {link = "BlueItalic"},
pythonExClass = {link = "BlueItalic"},
shDerefOff = {link = "BlueItalic"},
shDerefSimple = {link = "BlueItalic"},
shDerefSpecial = {link = "BlueItalic"},
shDerefVar = {link = "BlueItalic"},
shVariable = {link = "BlueItalic"},
tsxTSConstructor = {link = "BlueItalic"},
["@annotation"] = {link = "BlueItalic"},
["@attribute"] = {link = "BlueItalic"},
["@lsp.type.class"] = {link = "BlueItalic"},
["@lsp.type.enum"] = {link = "BlueItalic"},
["@lsp.type.interface"] = {link = "BlueItalic"},
["@lsp.type.namespace"] = {link = "BlueItalic"},
["@lsp.type.struct"] = {link = "BlueItalic"},
["@lsp.type.type"] = {link = "BlueItalic"},
["@lsp.type.typeParameter"] = {link = "BlueItalic"},
["@module"] = {link = "BlueItalic"},
["@namespace"] = {link = "BlueItalic"},
["@tag"] = {link = "BlueItalic"},
["@type"] = {link = "BlueItalic"},
["@type.builtin"] = {link = "BlueItalic"},
["@type.definition"] = {link = "BlueItalic"},
BlueSign = {fg = "#76cce0"},
DiagnosticSignInfo = {link = "BlueSign"},
Boolean = {fg = "#b39df3"},
diffChanged = {link = "Changed"},
Character = {fg = "#e7c664"},
ColorColumn = {bg = "#33353f"},
Comment = {fg = "#7f8490", italic = true},
SnacksPickerDir = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@lsp.type.comment"] = {link = "Comment"},
Conceal = {fg = "#595f6f"},
BlinkCmpGhostText = {link = "Conceal"},
Conditional = {fg = "#fc5d7c"},
Constant = {fg = "#f39660"},
["@markup.link"] = {link = "Constant"},
["@text.reference"] = {link = "Constant"},
CurrentWord = {bold = true},
LspReferenceRead = {link = "CurrentWord"},
LspReferenceText = {link = "CurrentWord"},
LspReferenceWrite = {link = "CurrentWord"},
Cursor = {bg = "#e2e2e3"},
TermCursor = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorColumn = {bg = "#33353f"},
CursorLine = {bg = "#33353f"},
SnacksPickerListCursorLine = {link = "CursorLine"},
CursorLineNr = {fg = "#e2e2e3"},
Debug = {fg = "#e7c664"},
["@debug"] = {link = "Debug"},
["@keyword.debug"] = {link = "Debug"},
Define = {fg = "#fc5d7c"},
["@define"] = {link = "Define"},
["@keyword.directive.define"] = {link = "Define"},
Delimiter = {fg = "#e2e2e3"},
["@punctuation"] = {link = "Delimiter"},
DiagnosticDeprecated = {sp = "#e2e2e3", strikethrough = true},
["@lsp.mod.deprecated"] = {link = "DiagnosticDeprecated"},
DiagnosticError = {fg = "#fc5d7c"},
DiagnosticHint = {fg = "#b39df3"},
DiagnosticInfo = {fg = "#76cce0"},
DiagnosticOk = {fg = "#9ed072"},
DiagnosticUnderlineError = {sp = "#fc5d7c", undercurl = true},
DiagnosticUnderlineHint = {sp = "#b39df3", undercurl = true},
DiagnosticUnderlineInfo = {sp = "#76cce0", undercurl = true},
DiagnosticUnderlineOk = {sp = "#9ed072", undercurl = true},
DiagnosticUnderlineWarn = {sp = "#e7c664", undercurl = true},
DiagnosticUnnecessary = {fg = "#7f8490"},
DiagnosticWarn = {fg = "#e7c664"},
DiffAdd = {bg = "#394634"},
DiffChange = {bg = "#354157"},
DiffDelete = {bg = "#55393d"},
DiffText = {fg = "#2c2e34", bg = "#76cce0"},
Directory = {fg = "#9ed072"},
EndOfBuffer = {fg = "#414550"},
Error = {fg = "#fc5d7c"},
["@error"] = {link = "Error"},
ErrorFloat = {fg = "#fc5d7c"},
DiagnosticFloatingError = {link = "ErrorFloat"},
ErrorMsg = {fg = "#fc5d7c", bold = true, underline = true},
Exception = {fg = "#fc5d7c"},
Fg = {fg = "#e2e2e3"},
BlinkCmpKindText = {link = "Fg"},
NeoTreeGitUntracked = {link = "Fg"},
TroubleText = {link = "Fg"},
htmlTSText = {link = "Fg"},
luaBraces = {link = "Fg"},
phpIdentifier = {link = "Fg"},
phpInterpVarname = {link = "Fg"},
phpMethodsVar = {link = "Fg"},
phpParent = {link = "Fg"},
phpVarSelector = {link = "Fg"},
shRange = {link = "Fg"},
["@constant"] = {link = "Fg"},
["@lsp.type.parameter"] = {link = "Fg"},
["@lsp.type.variable"] = {link = "Fg"},
["@none"] = {link = "Fg"},
["@parameter"] = {link = "Fg"},
["@parameter.reference"] = {link = "Fg"},
["@string.special.symbol"] = {link = "Fg"},
["@symbol"] = {link = "Fg"},
["@text.gitcommit"] = {link = "Fg"},
["@variable"] = {link = "Fg"},
["@variable.parameter"] = {link = "Fg"},
Float = {fg = "#b39df3"},
FloatBorder = {fg = "#7f8490", bg = "#363944"},
FloatTitle = {fg = "#fc5d7c", bg = "#414550", bold = true},
FoldColumn = {fg = "#595f6f"},
Folded = {fg = "#7f8490"},
Function = {fg = "#9ed072"},
Green = {fg = "#9ed072"},
Added = {link = "Green"},
BlinkCmpKindConstructor = {link = "Green"},
BlinkCmpKindField = {link = "Green"},
BlinkCmpKindFile = {link = "Green"},
BlinkCmpKindFunction = {link = "Green"},
BlinkCmpKindMethod = {link = "Green"},
NeoTreeGitAdded = {link = "Green"},
SnacksDashboardKey = {link = "Green"},
gitcommitFile = {link = "Green"},
phpDefine = {link = "Green"},
phpFunction = {link = "Green"},
phpMethod = {link = "Green"},
phpSpecialFunction = {link = "Green"},
pythonBuiltinFunc = {link = "Green"},
pythonFunction = {link = "Green"},
shFunction = {link = "Green"},
["@constructor"] = {link = "Green"},
["@function"] = {link = "Green"},
["@function.builtin"] = {link = "Green"},
["@function.call"] = {link = "Green"},
["@function.macro"] = {link = "Green"},
["@function.method"] = {link = "Green"},
["@function.method.call"] = {link = "Green"},
["@lsp.type.decorator"] = {link = "Green"},
["@lsp.type.function"] = {link = "Green"},
["@lsp.type.method"] = {link = "Green"},
["@lsp.type.regexp"] = {link = "Green"},
["@markup.list.checked"] = {link = "Green"},
["@method"] = {link = "Green"},
["@method.call"] = {link = "Green"},
["@string.escape"] = {link = "Green"},
["@string.regex"] = {link = "Green"},
["@string.regexp"] = {link = "Green"},
["@tag.attribute"] = {link = "Green"},
["@text"] = {link = "Green"},
["@text.todo.checked"] = {link = "Green"},
GreenSign = {fg = "#9ed072"},
DiagnosticSignOk = {link = "GreenSign"},
Grey = {fg = "#7f8490"},
NeoTreeDimText = {link = "Grey"},
NeoTreeGitIgnored = {link = "Grey"},
SnacksDashboardDir = {link = "Grey"},
SnacksPickerBorder = {link = "Grey"},
SnacksPickerTotals = {link = "Grey"},
TroubleCode = {link = "Grey"},
TroubleSource = {link = "Grey"},
VirtualTextError = {link = "Grey"},
VirtualTextHint = {link = "Grey"},
VirtualTextInfo = {link = "Grey"},
VirtualTextOk = {link = "Grey"},
VirtualTextWarning = {link = "Grey"},
diffLine = {link = "Grey"},
gitcommitArrow = {link = "Grey"},
gitcommitDiscarded = {link = "Grey"},
gitcommitOnBranch = {link = "Grey"},
gitcommitSelected = {link = "Grey"},
gitcommitUnmerged = {link = "Grey"},
gitcommitUntracked = {link = "Grey"},
pythonCoding = {link = "Grey"},
pythonDot = {link = "Grey"},
["@conceal"] = {link = "Grey"},
["@markup.quote"] = {link = "Grey"},
["@markup.strike"] = {link = "Grey"},
["@punctuation.bracket"] = {link = "Grey"},
["@punctuation.delimiter"] = {link = "Grey"},
["@strike"] = {link = "Grey"},
["@text.strike"] = {link = "Grey"},
HintFloat = {fg = "#b39df3"},
DiagnosticFloatingHint = {link = "HintFloat"},
Identifier = {fg = "#f39660"},
Ignore = {fg = "#7f8490"},
["@markup.list.unchecked"] = {link = "Ignore"},
["@text.todo.unchecked"] = {link = "Ignore"},
IncSearch = {fg = "#2c2e34", bg = "#ff6077"},
CurSearch = {link = "IncSearch"},
Include = {fg = "#fc5d7c"},
pythonInclude = {link = "Include"},
InfoFloat = {fg = "#76cce0"},
DiagnosticFloatingInfo = {link = "InfoFloat"},
LspInlayHint = {link = "InlayHints"},
Keyword = {fg = "#fc5d7c"},
Label = {fg = "#b39df3"},
LineNr = {fg = "#595f6f"},
InlayHints = {link = "LineNr"},
Macro = {fg = "#b39df3"},
["@markup.environment"] = {link = "Macro"},
["@text.environment"] = {link = "Macro"},
MatchParen = {bg = "#414550"},
ModeMsg = {fg = "#e2e2e3", bold = true},
MoreMsg = {fg = "#76cce0", bold = true},
NonText = {fg = "#414550"},
NeoTreeIndentMarker = {link = "NonText"},
NormalFloat = {fg = "#e2e2e3", bg = "#363944"},
NormalNC = {fg = "#e2e2e3"},
Number = {fg = "#b39df3"},
OkFloat = {fg = "#9ed072"},
DiagnosticFloatingOk = {link = "OkFloat"},
Operator = {fg = "#fc5d7c"},
Orange = {fg = "#f39660"},
BlinkCmpKindConstant = {link = "Orange"},
BlinkCmpKindProperty = {link = "Orange"},
BlinkCmpKindVariable = {link = "Orange"},
diffNewFile = {link = "Orange"},
["@field"] = {link = "Orange"},
["@lsp.type.enumMember"] = {link = "Orange"},
["@lsp.type.property"] = {link = "Orange"},
["@property"] = {link = "Orange"},
["@string.special.symbol.elixir"] = {link = "Orange"},
["@string.special.symbol.ruby"] = {link = "Orange"},
["@variable.member"] = {link = "Orange"},
OrangeItalic = {fg = "#f39660"},
phpNullValue = {link = "OrangeItalic"},
pythonBuiltinObj = {link = "OrangeItalic"},
pythonDecorator = {link = "OrangeItalic"},
pythonDecoratorName = {link = "OrangeItalic"},
pythonDottedName = {link = "OrangeItalic"},
pythonNone = {link = "OrangeItalic"},
tsxTSTag = {link = "OrangeItalic"},
Pmenu = {fg = "#e2e2e3", bg = "#363944"},
PmenuExtra = {fg = "#7f8490", bg = "#363944"},
PmenuKind = {fg = "#9ed072", bg = "#363944"},
PmenuSbar = {bg = "#363944"},
PmenuSel = {fg = "#2c2e34", bg = "#85d3f2", blend = 0},
PmenuThumb = {bg = "#7f8490"},
PreCondit = {fg = "#fc5d7c"},
PreProc = {fg = "#fc5d7c"},
pythonImport = {link = "PreProc"},
["@keyword.directive"] = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Purple = {fg = "#b39df3"},
BlinkCmpKindEnumMember = {link = "Purple"},
BlinkCmpKindUnit = {link = "Purple"},
BlinkCmpKindValue = {link = "Purple"},
NeoTreeGitStaged = {link = "Purple"},
NeoTreeGitUnstaged = {link = "Purple"},
diffFile = {link = "Purple"},
diffIndexLine = {link = "Purple"},
phpInterpSimpleCurly = {link = "Purple"},
shOption = {link = "Purple"},
["@boolean"] = {link = "Purple"},
["@float"] = {link = "Purple"},
["@lsp.type.number"] = {link = "Purple"},
["@number"] = {link = "Purple"},
["@number.float"] = {link = "Purple"},
PurpleItalic = {fg = "#b39df3"},
["@constant.builtin"] = {link = "PurpleItalic"},
["@constant.macro"] = {link = "PurpleItalic"},
["@lsp.type.macro"] = {link = "PurpleItalic"},
["@lsp.typemod.variable.defaultLibrary.javascript"] = {link = "PurpleItalic"},
["@lsp.typemod.variable.defaultLibrary.javascriptreact"] = {link = "PurpleItalic"},
["@lsp.typemod.variable.defaultLibrary.typescript"] = {link = "PurpleItalic"},
["@lsp.typemod.variable.defaultLibrary.typescriptreact"] = {link = "PurpleItalic"},
["@variable.builtin"] = {link = "PurpleItalic"},
PurpleSign = {fg = "#b39df3"},
DiagnosticSignHint = {link = "PurpleSign"},
Question = {fg = "#e7c664"},
QuickFixLine = {fg = "#76cce0", bold = true},
Red = {fg = "#fc5d7c"},
BlinkCmpKindKey = {link = "Red"},
BlinkCmpKindKeyword = {link = "Red"},
BlinkCmpKindNamespace = {link = "Red"},
BlinkCmpKindOperator = {link = "Red"},
BlinkCmpKindPackage = {link = "Red"},
NeoTreeGitDeleted = {link = "Red"},
Removed = {link = "Red"},
gitcommitSummary = {link = "Red"},
phpComparison = {link = "Red"},
phpLabel = {link = "Red"},
phpMemberSelector = {link = "Red"},
phpStructure = {link = "Red"},
pythonConditional = {link = "Red"},
pythonException = {link = "Red"},
pythonExceptions = {link = "Red"},
pythonOperator = {link = "Red"},
pythonRepeat = {link = "Red"},
shFunctionKey = {link = "Red"},
shVarAssign = {link = "Red"},
["@conditional"] = {link = "Red"},
["@exception"] = {link = "Red"},
["@include"] = {link = "Red"},
["@keyword"] = {link = "Red"},
["@keyword.conditional"] = {link = "Red"},
["@keyword.exception"] = {link = "Red"},
["@keyword.function"] = {link = "Red"},
["@keyword.import"] = {link = "Red"},
["@keyword.operator"] = {link = "Red"},
["@keyword.repeat"] = {link = "Red"},
["@keyword.return"] = {link = "Red"},
["@keyword.storage"] = {link = "Red"},
["@label"] = {link = "Red"},
["@lsp.type.events"] = {link = "Red"},
["@lsp.type.keyword"] = {link = "Red"},
["@lsp.type.modifier"] = {link = "Red"},
["@lsp.type.operator"] = {link = "Red"},
["@operator"] = {link = "Red"},
["@repeat"] = {link = "Red"},
["@storageclass"] = {link = "Red"},
["@storageclass.lifetime"] = {link = "Red"},
["@tag.delimiter"] = {link = "Red"},
["@type.qualifier"] = {link = "Red"},
RedItalic = {fg = "#fc5d7c"},
SnacksDashboardTitle = {link = "RedItalic"},
RedSign = {fg = "#fc5d7c"},
DiagnosticSignError = {link = "RedSign"},
diffRemoved = {link = "Removed"},
Repeat = {fg = "#fc5d7c"},
Search = {fg = "#2c2e34", bg = "#a7df78"},
LspSignatureActiveParameter = {link = "Search"},
SignColumn = {fg = "#e2e2e3"},
SnacksPickerMatch = {fg = "#9ed072", bold = true},
SnacksPickerFooter = {link = "SnacksPickerTitle"},
Special = {fg = "#b39df3"},
SnacksPickerGitStatus = {link = "Special"},
["@attribute.builtin"] = {link = "Special"},
["@markup"] = {link = "Special"},
["@module.builtin"] = {link = "Special"},
["@tag.builtin"] = {link = "Special"},
["@variable.parameter.builtin"] = {link = "Special"},
SpecialChar = {fg = "#b39df3"},
["@character.printf"] = {link = "SpecialChar"},
["@character.special"] = {link = "SpecialChar"},
["@markup.link.label"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpecialComment = {fg = "#7f8490", italic = true},
SpecialKey = {fg = "#b39df3"},
SpellBad = {sp = "#fc5d7c", undercurl = true},
SpellCap = {sp = "#e7c664", undercurl = true},
SpellLocal = {sp = "#76cce0", undercurl = true},
SpellRare = {sp = "#b39df3", undercurl = true},
Statement = {fg = "#fc5d7c"},
StatusLine = {fg = "#e2e2e3", bg = "#3b3e48"},
StatusLineNC = {fg = "#7f8490", bg = "#33353f"},
StatusLineTerm = {fg = "#e2e2e3", bg = "#3b3e48"},
StatusLineTermNC = {fg = "#7f8490", bg = "#33353f"},
StorageClass = {fg = "#76cce0"},
String = {fg = "#e7c664"},
["@markup.raw"] = {link = "String"},
["@text.literal"] = {link = "String"},
Structure = {fg = "#76cce0"},
Substitute = {fg = "#2c2e34", bg = "#e7c664"},
TSDanger = {fg = "#2c2e34", bg = "#fc5d7c", bold = true},
["@comment.error"] = {link = "TSDanger"},
["@text.danger"] = {link = "TSDanger"},
TSEmphasis = {italic = true},
["@markup.emphasis"] = {link = "TSEmphasis"},
["@text.emphasis"] = {link = "TSEmphasis"},
TSNote = {fg = "#2c2e34", bg = "#9ed072", bold = true},
["@comment.note"] = {link = "TSNote"},
["@markup.note"] = {link = "TSNote"},
["@text.note"] = {link = "TSNote"},
TSStrong = {bold = true},
["@markup.strong"] = {link = "TSStrong"},
["@text.strong"] = {link = "TSStrong"},
TSURI = {fg = "#76cce0", underline = true},
["@markup.link.url"] = {link = "TSURI"},
["@string.special.uri"] = {link = "TSURI"},
["@text.uri"] = {link = "TSURI"},
["@uri"] = {link = "TSURI"},
TSUnderline = {underline = true},
["@markup.underline"] = {link = "TSUnderline"},
["@text.underline"] = {link = "TSUnderline"},
TSWarning = {fg = "#2c2e34", bg = "#e7c664", bold = true},
["@comment.warning"] = {link = "TSWarning"},
["@text.warning"] = {link = "TSWarning"},
TabLine = {fg = "#e2e2e3", bg = "#414550"},
TabLineFill = {fg = "#7f8490", bg = "#33353f"},
TabLineSel = {fg = "#2c2e34", bg = "#ff6077"},
Tag = {fg = "#f39660"},
Title = {fg = "#fc5d7c", bold = true},
NeoTreeRootName = {link = "Title"},
SnacksPickerTitle = {link = "Title"},
["@markup.heading"] = {link = "Title"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#2c2e34", bg = "#76cce0", bold = true},
["@comment.todo"] = {link = "Todo"},
["@text.todo"] = {link = "Todo"},
["@todo"] = {link = "Todo"},
Type = {fg = "#76cce0"},
["@markup.environment.name"] = {link = "Type"},
["@text.environment.name"] = {link = "Type"},
Typedef = {fg = "#fc5d7c"},
Underlined = {underline = true},
["@string.special.url"] = {link = "Underlined"},
VertSplit = {fg = "#181819"},
WinSeparator = {link = "VertSplit"},
DiagnosticVirtualTextError = {link = "VirtualTextError"},
DiagnosticVirtualTextHint = {link = "VirtualTextHint"},
LspCodeLensSeparator = {link = "VirtualTextHint"},
DiagnosticVirtualTextInfo = {link = "VirtualTextInfo"},
LspCodeLens = {link = "VirtualTextInfo"},
DiagnosticVirtualTextOk = {link = "VirtualTextOk"},
DiagnosticVirtualTextWarn = {link = "VirtualTextWarning"},
Visual = {bg = "#414550"},
VisualNOS = {bg = "#414550", underline = true},
WarningFloat = {fg = "#e7c664"},
DiagnosticFloatingWarn = {link = "WarningFloat"},
WarningMsg = {fg = "#e7c664", bold = true},
Whitespace = {fg = "#414550"},
WinBar = {fg = "#e2e2e3", bg = "#3b3e48", bold = true},
WinBarNC = {fg = "#7f8490", bg = "#33353f"},
Yellow = {fg = "#e7c664"},
BlinkCmpKindArray = {link = "Yellow"},
BlinkCmpKindBoolean = {link = "Yellow"},
BlinkCmpKindColor = {link = "Yellow"},
BlinkCmpKindDefault = {link = "Yellow"},
BlinkCmpKindEvent = {link = "Yellow"},
BlinkCmpKindFolder = {link = "Yellow"},
BlinkCmpKindNull = {link = "Yellow"},
BlinkCmpKindNumber = {link = "Yellow"},
BlinkCmpKindObject = {link = "Yellow"},
BlinkCmpKindReference = {link = "Yellow"},
BlinkCmpKindSnippet = {link = "Yellow"},
BlinkCmpKindString = {link = "Yellow"},
NeoTreeGitConflict = {link = "Yellow"},
SnacksDashboardDesc = {link = "Yellow"},
SnacksPickerToggle = {link = "Yellow"},
diffOldFile = {link = "Yellow"},
phpNowDoc = {link = "Yellow"},
shQuote = {link = "Yellow"},
["@character"] = {link = "Yellow"},
["@lsp.type.string"] = {link = "Yellow"},
["@markup.list"] = {link = "Yellow"},
["@markup.math"] = {link = "Yellow"},
["@math"] = {link = "Yellow"},
["@punctuation.special"] = {link = "Yellow"},
["@string"] = {link = "Yellow"},
["@text.math"] = {link = "Yellow"},
YellowSign = {fg = "#e7c664"},
DiagnosticSignWarn = {link = "YellowSign"},
["@diff.plus"] = {link = "diffAdded"},
["@text.diff.add"] = {link = "diffAdded"},
["@diff.delta"] = {link = "diffChanged"},
["@diff.minus"] = {link = "diffRemoved"},
["@text.diff.delete"] = {link = "diffRemoved"},
["@text.html"] = {link = "htmlTSText"},
luaTSConstructor = {link = "luaBraces"},
["@constructor.lua"] = {link = "luaTSConstructor"},
markdownH1 = {fg = "#fc5d7c", bold = true},
["@markup.heading.1.markdown"] = {link = "markdownH1"},
markdownH2 = {fg = "#f39660", bold = true},
["@markup.heading.2.markdown"] = {link = "markdownH2"},
markdownH3 = {fg = "#e7c664", bold = true},
["@markup.heading.3.markdown"] = {link = "markdownH3"},
markdownH4 = {fg = "#9ed072", bold = true},
["@markup.heading.4.markdown"] = {link = "markdownH4"},
markdownH5 = {fg = "#76cce0", bold = true},
["@markup.heading.5.markdown"] = {link = "markdownH5"},
markdownH6 = {fg = "#b39df3", bold = true},
["@markup.heading.6.markdown"] = {link = "markdownH6"},
["@constructor.tsx"] = {link = "tsxTSConstructor"},
["@tag.tsx"] = {link = "tsxTSTag"},
["@markup.heading.1.marker.markdown"] = {link = "@conceal"},
["@markup.heading.2.marker.markdown"] = {link = "@conceal"},
["@markup.heading.3.marker.markdown"] = {link = "@conceal"},
["@markup.heading.4.marker.markdown"] = {link = "@conceal"},
["@markup.heading.5.marker.markdown"] = {link = "@conceal"},
["@markup.heading.6.marker.markdown"] = {link = "@conceal"},
["@markup.heading.1.delimiter.vimdoc"] = {sp = "#e2e2e3", nocombine = true, underdouble = true},
["@markup.heading.2.delimiter.vimdoc"] = {sp = "#e2e2e3", nocombine = true, underline = true},
["@markup.italic"] = {italic = true},
["@markup.strikethrough"] = {strikethrough = true},
["@lsp.type.event"] = {link = "@type"},
-- PATCH_CLOSE
}

for group, attrs in pairs(groups) do
  vim.api.nvim_set_hl(0, group, attrs)
end

-- :terminal palette, as sonokai sets it: black, red, green, yellow, blue, purple, orange, fg;
-- the bright half repeats it with grey for black
for i, color in ipairs({
  "#181819", "#fc5d7c", "#9ed072", "#e7c664", "#76cce0", "#b39df3", "#f39660", "#e2e2e3",
  "#7f8490", "#fc5d7c", "#9ed072", "#e7c664", "#76cce0", "#b39df3", "#f39660", "#e2e2e3",
}) do
  vim.g["terminal_color_" .. (i - 1)] = color
end
