-- GENERATED by bin/theme-sync from theme.palette — do not edit by hand.
-- mode: dark · family: opencode
vim.o.background = "dark"
require("mini.base16").setup({
  palette = {
    base00 = "#0f0f0f",          -- background
    base01 = "#15141b",       -- statusline, popups
    base02 = "#2d2d2d",   -- selection, cursorline
    base03 = "#858585",       -- comments, line numbers
    base04 = "#b9b9ba", -- dark foreground (statusline text)
    base05 = "#edecee",          -- default text
    base06 = "#ffffff",
    base07 = "#ffffff",
    base08 = "#ff6767",         -- variables, tags, diff delete
    base09 = "#ffca85",      -- numbers, constants
    base0A = "#ffca85",      -- types, search
    base0B = "#9dff65",       -- strings, diff add
    base0C = "#61ffca",        -- regex, escapes
    base0D = "#6b9aee",      -- functions (primary accent)
    base0E = "#f694ff",        -- keywords
    base0F = "#82e2ff",        -- delimiters, deprecated
  },
  use_cterm = false,
})
vim.g.colors_name = "terminal"
for _, group in ipairs({ "Normal", "NormalNC", "SignColumn", "EndOfBuffer", "LineNr", "FoldColumn" }) do
  vim.api.nvim_set_hl(0, group, vim.tbl_extend("force", vim.api.nvim_get_hl(0, { name = group }), { bg = "NONE" }))
end
