-- GENERATED by bin/theme-sync from theme.palette.light — do not edit by hand.
-- mode: light · family: opencode
vim.o.background = "light"
require("mini.base16").setup({
  palette = {
    base00 = "#ffffff",          -- background
    base01 = "#ebebeb",       -- statusline, popups
    base02 = "#d4d4d4",   -- selection, cursorline
    base03 = "#6a6a6a",       -- comments, line numbers
    base04 = "#424242", -- dark foreground (statusline text)
    base05 = "#1a1a1a",          -- default text
    base06 = "#000000",
    base07 = "#000000",
    base08 = "#c72e33",         -- variables, tags, diff delete
    base09 = "#915f1a",      -- numbers, constants
    base0A = "#915f1a",      -- types, search
    base0B = "#2f7743",       -- strings, diff add
    base0C = "#2a7480",        -- regex, escapes
    base0D = "#2769c3",      -- functions (primary accent)
    base0E = "#7857b4",        -- keywords
    base0F = "#18719e",        -- delimiters, deprecated
  },
  use_cterm = false,
})
vim.g.colors_name = "terminal"
for _, group in ipairs({ "Normal", "NormalNC", "SignColumn", "EndOfBuffer", "LineNr", "FoldColumn" }) do
  vim.api.nvim_set_hl(0, group, vim.tbl_extend("force", vim.api.nvim_get_hl(0, { name = group }), { bg = "NONE" }))
end
