-- GENERATED by bin/theme-sync from theme.palette.claude-dark — do not edit by hand.
-- mode: dark · family: claude
vim.o.background = "dark"
require("mini.base16").setup({
  palette = {
    base00 = "#1a1a1a",          -- background
    base01 = "#262626",       -- statusline, popups
    base02 = "#264f78",   -- selection, cursorline
    base03 = "#999999",       -- comments, line numbers
    base04 = "#cccccc", -- dark foreground (statusline text)
    base05 = "#ffffff",          -- default text
    base06 = "#ffffff",
    base07 = "#ffffff",
    base08 = "#ff6b80",         -- variables, tags, diff delete
    base09 = "#ffc107",      -- numbers, constants
    base0A = "#ffc107",      -- types, search
    base0B = "#4eba65",       -- strings, diff add
    base0C = "#4a9a90",        -- regex, escapes
    base0D = "#b1b9f9",      -- functions (primary accent)
    base0E = "#fd5db1",        -- keywords
    base0F = "#7ab4e8",        -- delimiters, deprecated
  },
  use_cterm = false,
})
vim.g.colors_name = "terminal"
for _, group in ipairs({ "Normal", "NormalNC", "SignColumn", "EndOfBuffer", "LineNr", "FoldColumn" }) do
  vim.api.nvim_set_hl(0, group, vim.tbl_extend("force", vim.api.nvim_get_hl(0, { name = group }), { bg = "NONE" }))
end
