-- Everything about the colorscheme: this directory is on 'runtimepath' (core.lua), so colors/ here works as
-- usual. The only colorscheme is "terminal" (colors/terminal.lua): generated by ~/.dotfiles/bin/theme-sync from
-- the terminal palette, built on mini.base16. This file applies it, holds highlight tweaks on top of it and the
-- lazy.nvim spec of mini.base16 (init.lua adds it to its spec).

vim.api.nvim_create_autocmd("ColorScheme", {
  callback = function()
    -- приглушённые направляющие отступов snacks.indent (обычные и текущий scope), для светлой и тёмной темы
    local light = vim.o.background == "light"
    vim.api.nvim_set_hl(0, "SnacksIndent", { fg = light and "#e4dcd4" or "#2c2c30" })
    vim.api.nvim_set_hl(0, "SnacksIndentScope", { fg = light and "#d3c7bb" or "#4d4766" })

    -- float and popup-menu borders: mini.base16 draws them in the text color, use the palette's subtle
    -- border color instead (base02, the same as the split lines). Plugin borders (snacks picker, lazy,
    -- neo-tree, trouble) link to FloatBorder.
    local border = MiniBase16 and MiniBase16.config.palette and MiniBase16.config.palette.base02
    if border then
      local float_bg = vim.api.nvim_get_hl(0, { name = "NormalFloat", link = false }).bg
      vim.api.nvim_set_hl(0, "FloatBorder", { fg = border, bg = float_bg })
      vim.api.nvim_set_hl(0, "PmenuBorder", { fg = border, bg = vim.api.nvim_get_hl(0, { name = "Pmenu", link = false }).bg })
    end
  end,
})

return {
  {
    "echasnovski/mini.base16",
    version = "^0.18.0",
    lazy = false,
    priority = 1000, -- before other plugins, so they set their default highlights on top of it
    config = function()
      vim.cmd.colorscheme("terminal")
    end,
  },
}
