-- Everything about colorschemes: this directory is on 'runtimepath' (core.lua), so colors/ and lua/ here
-- work as usual. colors/ holds the local colorschemes, lua/lush_theme/ the lush source of sonokai,
-- shipwright_build.lua compiles it. This file: highlight tweaks shared by all themes and the lazy.nvim specs
-- of the theme plugins (init.lua adds them to its spec).

-- приглушённые направляющие отступов snacks.indent (обычные и текущий scope), для светлой и тёмной темы
vim.api.nvim_create_autocmd("ColorScheme", {
  callback = function()
    local light = vim.o.background == "light"
    vim.api.nvim_set_hl(0, "SnacksIndent", { fg = light and "#e4dcd4" or "#2c2c30" })
    vim.api.nvim_set_hl(0, "SnacksIndentScope", { fg = light and "#d3c7bb" or "#4d4766" })
  end,
})

return {
  -- colors/sonokai.lua is compiled, it needs no plugin at runtime. Its source is the lush spec in
  -- lua/lush_theme/sonokai.lua: :Lushify in that buffer previews edits live,
  -- :Shipwright themes/shipwright_build.lua (from ~/.config/nvim) rebuilds colors/sonokai.lua from it.
  { "rktjmp/lush.nvim", cmd = "Lushify" },
  { "rktjmp/shipwright.nvim", cmd = "Shipwright", dependencies = { "rktjmp/lush.nvim" } },
  -- colorscheme "terminal" (colors/terminal.lua, generated by ~/.dotfiles/bin/theme-sync) is built on
  -- mini.base16; loaded on require so it stays selectable from the colorscheme picker
  { "echasnovski/mini.base16", version = "^0.18.0", lazy = true },

  -- colorschemes on trial: lazy, so they cost nothing at startup; the colorscheme picker (<leader>uC)
  -- lists them and lazy.nvim loads a plugin when its colorscheme is picked. All transparent, like sonokai.
  {
    "loctvl842/monokai-pro.nvim",
    lazy = true,
    opts = { transparent_background = true, filter = "spectrum" },
  },
  { "catppuccin/nvim", name = "catppuccin", lazy = true, opts = { transparent_background = true } },
  {
    "folke/tokyonight.nvim",
    lazy = true,
    opts = {
      transparent = true,
      on_colors = function(c)
        -- burgundy style: the active float border is derived from blue1 (types), use burgundy instead
        if c.burgundy then
          c.border_highlight = c.burgundy.border
        end
      end,
    },
    config = function(_, opts)
      -- extra style "burgundy" (colors/tokyonight-burgundy.lua): night with a dark brown background, warm
      -- greys and burgundy accents. Set as a palette, before tokyonight derives selection/search/diff from it.
      -- Text accent #cc5a72 is the darkest burgundy with 4.5:1 contrast on the background; deep burgundy
      -- #7a1f33 is only used as a background (search, selection).
      require("tokyonight.colors").styles.burgundy = function()
        return vim.tbl_deep_extend("force", vim.deepcopy(require("tokyonight.colors.night")), {
          bg = "#1e1612",
          bg_dark = "#18110e",
          bg_dark1 = "#120c0a",
          bg_highlight = "#2b211b", -- cursorline
          blue = "#cc5a72",         -- main accent: functions, titles, directories
          blue0 = "#7a1f33",        -- search, selection (blended)
          blue7 = "#4a2630",        -- diff text, inlay hint background
          fg_gutter = "#4a3a30",
          dark3 = "#5e4c41",
          dark5 = "#8f7d70",
          comment = "#86746a",
          terminal_black = "#4d3e34",
          burgundy = { border = "#a8324a" },
        })
      end
      require("tokyonight").setup(opts)
    end,
  },
  { "rebelot/kanagawa.nvim", lazy = true, opts = { transparent = true } },
  {
    -- main colorscheme: dayfox in the light macOS appearance, carbonfox in the dark one, switching while
    -- running. Loaded first (priority) so other plugins set their default highlights on top of it.
    "EdenEast/nightfox.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      -- transparent: the background comes from the terminal, so tmux can dim inactive panes
      require("nightfox").setup({ options = { transparent = true } })

      local schemes = { light = "dayfox", dark = "carbonfox" }
      -- last seen appearance: startup applies it right away instead of waiting ~5 ms for `defaults read`,
      -- the real one is checked asynchronously right after
      local state_file = vim.fn.stdpath("state") .. "/appearance"
      local f = io.open(state_file)
      local mode = f and f:read("*l")
      if f then
        f:close()
      end
      mode = schemes[mode] and mode or "dark"
      vim.cmd.colorscheme(schemes[mode])

      if vim.fn.has("mac") == 0 then
        return
      end

      local function check()
        -- AppleInterfaceStyle is "Dark" in the dark appearance and missing (exit code 1) in the light one
        vim.system({ "defaults", "read", "-g", "AppleInterfaceStyle" }, { text = true }, function(res)
          local new = (res.stdout or ""):match("Dark") and "dark" or "light"
          if new == mode then
            return
          end
          mode = new
          vim.schedule(function()
            vim.cmd.colorscheme(schemes[mode])
            local out = io.open(state_file, "w")
            if out then
              out:write(mode)
              out:close()
            end
          end)
        end)
      end

      -- nothing notifies a terminal app of appearance changes: poll (async, a ~5 ms `defaults` run every
      -- 3 s) and check at once when the window gets focus back
      local timer = assert(vim.uv.new_timer())
      timer:start(0, 3000, check)
      vim.api.nvim_create_autocmd("FocusGained", { callback = check })
      vim.api.nvim_create_autocmd("VimLeavePre", {
        callback = function()
          timer:close()
        end,
      })
    end,
  },
  { "rose-pine/neovim", name = "rose-pine", lazy = true, opts = { styles = { transparency = true } } },
  -- {
  --   "f-person/auto-dark-mode.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {
  --     set_dark_mode = function()
  --       vim.cmd("colorscheme nightfox")
  --     end,
  --     set_light_mode = function()
  --       vim.cmd("colorscheme dayfox")
  --     end,
  --     update_interval = 3000,
  --     fallback = "light",
  --   },
  -- },
  -- {
  --   "EdenEast/nightfox.nvim",
  --   config = function()
  --     require("nightfox").setup({
  --       options = {
  --         -- transparent = true,
  --         terminal_colors = true,
  --       },
  --     })
  --     vim.cmd("colorscheme nightfox")
  --   end,
  -- },
}
