return {
    -- {
    --     "nvim-lualine/lualine.nvim",
    --     opts = {
    --         options = {
    --             icons_enabled = true,
    --             component_separators = "|",
    --             section_separators = "",
    --             disabled_filetypes = { 'packer', 'neo-tree' },
    --         },
    --         sections = {
    --             lualine_c = {
    --                 {
    --                     'filename',
    --                     path = 1,
    --                 }
    --             },
    --             lualine_x = {
    --                 -- {
    --                 --     function() return [[DEBUG: ]] .. require('dap').status() end,
    --                 --     cond = function() return string.len(require('dap').status()) ~= 0 end,
    --                 --     color = "WarningMsg"
    --                 -- },
    --                 { "encoding" },
    --                 { "fileformat" },
    --                 { "filetype" },
    --             }
    --         }
    --     },
    -- },
}
